// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import ConditionalInputController from "controllers/conditional_input_controller"
application.register("conditional-input", ConditionalInputController)

import DateInputController from "controllers/date_input_controller"
application.register("date-input", DateInputController)

import MoneyInputController from "controllers/money_input_controller"
application.register("money-input", MoneyInputController)

import ToggleController from "controllers/toggle_controller"
application.register("toggle", ToggleController)
